
class Closing_Error(Exception):
    pass